export const MAIN_PAGE_URL = '/'
export const LIBRARY_PAGE_URL = '/library'
export const MARKED_VERBS_PAGE_URL = '/marked-verbs'
export const PREPARE_LESSON_PAGE_URL = '/prepare'
export const LESSON_PAGE_URL = '/lesson'
export const SETTINGS_PAGE_URL = '/settings'